// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq4t8937B972GnYutGdmVHeRL6KQvr1CE',
    appId: '1:1026233999300:web:3847359b7b4b334a3f8e91',
    messagingSenderId: '1026233999300',
    projectId: 'product-app-3c825',
    authDomain: 'product-app-3c825.firebaseapp.com',
    storageBucket: 'product-app-3c825.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHgtxcr83sjPmPj6pYJ6Gf3yBSXFjhbZM',
    appId: '1:1026233999300:android:1dc17671b429e8503f8e91',
    messagingSenderId: '1026233999300',
    projectId: 'product-app-3c825',
    storageBucket: 'product-app-3c825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUj572NAc6E65TJb8gHm_4HYcmsr1NLqE',
    appId: '1:1026233999300:ios:9d01f26e96f8b6233f8e91',
    messagingSenderId: '1026233999300',
    projectId: 'product-app-3c825',
    storageBucket: 'product-app-3c825.appspot.com',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUj572NAc6E65TJb8gHm_4HYcmsr1NLqE',
    appId: '1:1026233999300:ios:9d01f26e96f8b6233f8e91',
    messagingSenderId: '1026233999300',
    projectId: 'product-app-3c825',
    storageBucket: 'product-app-3c825.appspot.com',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq4t8937B972GnYutGdmVHeRL6KQvr1CE',
    appId: '1:1026233999300:web:a5f22b4215e8f3683f8e91',
    messagingSenderId: '1026233999300',
    projectId: 'product-app-3c825',
    authDomain: 'product-app-3c825.firebaseapp.com',
    storageBucket: 'product-app-3c825.appspot.com',
  );
}
